apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: comment
  name: comment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comment
  template:
    metadata:
      labels:
        app: comment
    spec:
      containers:
        - image: robotron1/spring_comment:v1.0
          name: comment
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: MONGO_URL
              value: mongodb://mongodb:27017/comment-db
          imagePullPolicy: Always
          resources:
            requests:
              memory: "732Mi"
              cpu: "500m"
            limits:
              memory: "732Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: rental-service
spec:
  selector:
    app: rental-service
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer