server.port: 7003

app:
  rental:
    host: localhost
    port: 7001
  comment:
    host: localhost
    port: 7002

---
spring.config.activate.on-profile: docker
server.port: 8080

app:
  rental:
    host: rental
    port: 8080
  comment:
    host: comment
    port: 8080

