# ... Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rental
  name: rental
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental
  template:
    metadata:
      labels:
        app: rental
    spec:
      containers:
        - image: robotron1/spring_rental:v1.0
          name: rental
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: MONGO_URL
              value: mongodb://mongodb:27017/rental-db
          imagePullPolicy: Always
          resources:
            requests:
              memory: "732Mi"
              cpu: "500m"
            limits:
              memory: "732Mi"
              cpu: "500m"
---
# ... Service
apiVersion: v1
kind: Service
metadata:
  name: rental
spec:
  selector:
    app: rental
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer