#spring:
#  application.name: gateway

#spring.cloud.gateway.routes:

#  - id: rental-service
#    uri: http://rental-service
#    predicates:
#      - Path=/api/rentals-and-comments/**

---
spring.config.activate.on-profile: docker
server:
  port: 8080

