server:
  port: 7001

spring.data.mongodb:
  host: localhost
  port: 27017
  database: rental-db


---
spring:
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      host: mongodb

server.port: 8080



